// File generated by FlutterFire CLI.
// This is a placeholder - users need to run `flutterfire configure` to generate this file

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeDbmiuFXR36PU2q1ICcGpjyfm8PTJa-4',
    appId: '1:811847941496:web:85b950696cd20203a1dc8d',
    messagingSenderId: '811847941496',
    projectId: 'wardrobeai-30887',
    authDomain: 'wardrobeai-30887.firebaseapp.com',
    storageBucket: 'wardrobeai-30887.firebasestorage.app',
    measurementId: 'G-XHXBG4VR0X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0y-vaO826Q5iq_GrjTL3JzkwyL9QU58U',
    appId: '1:811847941496:android:3510ca8b87c958f3a1dc8d',
    messagingSenderId: '811847941496',
    projectId: 'wardrobeai-30887',
    storageBucket: 'wardrobeai-30887.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5Fs1iay8ic6XCY2b0rx1cjERKeeSPhxk',
    appId: '1:811847941496:ios:87682cc1e63a7c5da1dc8d',
    messagingSenderId: '811847941496',
    projectId: 'wardrobeai-30887',
    storageBucket: 'wardrobeai-30887.firebasestorage.app',
    androidClientId: '811847941496-ia9mv8d2ua9ga97kgeph65gspvtt65i9.apps.googleusercontent.com',
    iosClientId: '811847941496-14b7tnoislull4omof6nvrrb7b80hnc8.apps.googleusercontent.com',
    iosBundleId: 'com.wardrobe.dressai',
  );

}